### ISSUE TITLE
Trouble running setup py

### ISSUE THREAD

**Issue by htrophy2020** [areed1192/python-trading-robot#3]
Had a few Warning issues when running the setup.py  that I need help with.  It may be an simple issue but I am a new user to Py and a novice at coding.  I could not locate "PATH" or I just dont understand what it is referencing.

Where exactly should I install these files listed in the Warnings.   Thanks for all your help!

Harry

Microsoft Windows [Version 10.0.18363.959]
(c) 2019 Microsoft Corporation. All rights reserved.
C:\Users\htrop\OneDrive\Documents\GitHub\python-trading-robot>pip install -e .
Obtaining file:///C:/Users/htrop/OneDrive/Documents/GitHub/python-trading-robot
Collecting td-ameritrade-python-api
  Downloading td_ameritrade_python_api-0.2.8-py3-none-any.whl (52 kB)
     |████████████████████████████████| 52 kB 204 kB/s
Collecting pandas
  Downloading pandas-1.1.0-cp38-cp38-win_amd64.whl (9.6 MB)
     |████████████████████████████████| 9.6 MB 1.1 MB/s
Collecting numpy
  Downloading numpy-1.19.1-cp38-cp38-win_amd64.whl (13.0 MB)
     |████████████████████████████████| 13.0 MB 127 kB/s
Collecting requests-oauthlib
  Downloading requests_oauthlib-1.3.0-py2.py3-none-any.whl (23 kB)
Collecting websockets
  Downloading websockets-8.1-cp38-cp38-win_amd64.whl (66 kB)
     |████████████████████████████████| 66 kB 96 kB/s
Collecting requests
  Downloading requests-2.24.0-py2.py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 54 kB/s
Collecting pyopenssl
  Downloading pyOpenSSL-19.1.0-py2.py3-none-any.whl (53 kB)
     |████████████████████████████████| 53 kB 265 kB/s
Collecting flask
  Downloading Flask-1.1.2-py2.py3-none-any.whl (94 kB)
     |████████████████████████████████| 94 kB 398 kB/s
Collecting python-dateutil>=2.7.3
  Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
     |████████████████████████████████| 227 kB 1.1 MB/s
Collecting pytz>=2017.2
  Downloading pytz-2020.1-py2.py3-none-any.whl (510 kB)
     |████████████████████████████████| 510 kB 595 kB/s
Collecting oauthlib>=3.0.0
  Downloading oauthlib-3.1.0-py2.py3-none-any.whl (147 kB)
     |████████████████████████████████| 147 kB 726 kB/s
Collecting chardet<4,>=3.0.2
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
     |████████████████████████████████| 133 kB 1.1 MB/s
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Downloading urllib3-1.25.10-py2.py3-none-any.whl (127 kB)
     |████████████████████████████████| 127 kB 656 kB/s
Collecting certifi>=2017.4.17
  Downloading certifi-2020.6.20-py2.py3-none-any.whl (156 kB)
     |████████████████████████████████| 156 kB 652 kB/s
Collecting idna<3,>=2.5
  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 562 kB/s
Collecting cryptography>=2.8
  Downloading cryptography-3.0-cp38-cp38-win_amd64.whl (1.5 MB)
     |████████████████████████████████| 1.5 MB 312 kB/s
Collecting six>=1.5.2
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting Werkzeug>=0.15
  Downloading Werkzeug-1.0.1-py2.py3-none-any.whl (298 kB)
     |████████████████████████████████| 298 kB 504 kB/s
Collecting click>=5.1
  Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
     |████████████████████████████████| 82 kB 144 kB/s
Collecting itsdangerous>=0.24
  Downloading itsdangerous-1.1.0-py2.py3-none-any.whl (16 kB)
Collecting Jinja2>=2.10.1
  Downloading Jinja2-2.11.2-py2.py3-none-any.whl (125 kB)
     |████████████████████████████████| 125 kB 726 kB/s
Collecting cffi!=1.11.3,>=1.8
  Downloading cffi-1.14.1-cp38-cp38-win_amd64.whl (178 kB)
     |████████████████████████████████| 178 kB 595 kB/s
Collecting MarkupSafe>=0.23
  Downloading MarkupSafe-1.1.1-cp38-cp38-win_amd64.whl (16 kB)
Collecting pycparser
  Downloading pycparser-2.20-py2.py3-none-any.whl (112 kB)
     |████████████████████████████████| 112 kB 726 kB/s
Installing collected packages: oauthlib, chardet, urllib3, certifi, idna, requests, requests-oauthlib, websockets, pycparser, cffi, six, cryptography, pyopenssl, Werkze
ug, click, itsdangerous, MarkupSafe, Jinja2, flask, td-ameritrade-python-api, python-dateutil, pytz, numpy, pandas, pyrobot
  WARNING: The script chardetect.exe is installed in 'C:\Users\htrop\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\
Python38\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script flask.exe is installed in 'C:\Users\htrop\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Pytho
n38\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script f2py.exe is installed in 'C:\Users\htrop\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python
38\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Running setup.py develop for pyrobot
Successfully installed Jinja2-2.11.2 MarkupSafe-1.1.1 Werkzeug-1.0.1 certifi-2020.6.20 cffi-1.14.1 chardet-3.0.4 click-7.1.2 cryptography-3.0 flask-1.1.2 idna-2.10 itsd
angerous-1.1.0 numpy-1.19.1 oauthlib-3.1.0 pandas-1.1.0 pycparser-2.20 pyopenssl-19.1.0 pyrobot python-dateutil-2.8.1 pytz-2020.1 requests-2.24.0 requests-oauthlib-1.

**Comment by charleswwilson** [comment]
Did you setup a virtual env for the project? If you are not familiar with this here is a link to a YouTube video that helped me a lot.

**Comment by areed1192** [comment]
It's more than likely that you haven't set the Python path for your system. Normally, you need to specify that when you install python on your system.
