### ISSUE TITLE
Papertrading - Caution

### ISSUE THREAD

**Issue by tmcquaig** [areed1192/python-trading-robot#5]
Papertrading does not appear to be supported for TD Ameritrade API but rather only for thinkorswim.

From [https://developer.tdameritrade.com/content/authentication-faq](https://developer.tdameritrade.com/content/authentication-faq)
"Note that a Paper Money account on the thinkorswim trading platform is only available through thinkorswim.  Thinkorswim is a separate environment from our API.  There is not a paper money feature available through our API."

**Comment by areed1192** [comment]
Yes, that is correct. TD Ameritrade **does not** offer paper trading through their API currently. The paper trading functionality currently in the python package is only used to mimic trading. No **actual orders are submitted** when you put it in paper trading mode, what instead happens is auto-generated orders are produced.

Now, this won't fit everyone's needs, especially if you're more concerned about orders being filled. However, the intent of this functionality is purely to see whether it can effectively **identify the signals**, **submit orders**, and then continue with **checking signals**.
