### ISSUE TITLE
Using MT4 instead of TD

### ISSUE THREAD

**Issue by misabdiel93** [areed1192/python-trading-robot#6]
For some reason I thought this was a program designed for the platform MetaTrader4. (I specifically looked up, "MT4 python trading bot." and this video popped up.) Now as I am reviewing it, I realize its not for MT4 its for TD ameritrade. Is there any way we can switch the platform?

**Comment by misabdiel93** [comment]
I have found to what is claimed to be a MT4 API. though I don't think its as beefy as this one.  The API is also on github, here is the link.

https://github.com/OpenTrading/OTMql4Py

**Comment by areed1192** [comment]
Unfortunately, currently, there is no plan to integrate the `MetaTrader4` API into the trading robot. The next client that would be integrated is `Interactive Brokers`. Not to say it couldn't be integrated but it requires a massive overhaul of the current package.
